name: C/C++ CI

on:
  push:
    branches: [ master ]
    branches: [ development ]
  pull_request:
    branches: [ master ]
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
